### ISSUE TITLE
unable to install 1.1.0

### ISSUE THREAD

**Issue by cociweb** [rhasspy/wyoming-faster-whisper#19]
Hello,
I've dod not found any pupblished and compiled version of 1.1.0 neither on pypi nor on piwheels. Therefore, I tried to install it from source. Unfortunatelly, the following error is poped up, and the install was unsuccessful:
```
pip3 install --no-cache v1.1.0.tar.gz 
Processing /v1.1.0.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-p5ad4qxy/setup.py", line 25, in <module>
          setup(
        File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 225, in finalize_options
          self.egg_name = self.name
                          ^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 126, in name
          return _normalization.safe_name(self.distribution.get_name())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/setuptools/_normalization.py", line 42, in safe_name
          return _UNSAFE_NAME_CHARS.sub("-", component)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'PosixPath'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I try to install the 1.0.2 from source (tar.gz) then there is no issue.

**Comment by cociweb** [comment]
I bet the issue is somewhere here around the hypens:
https://github.com/rhasspy/wyoming-faster-whisper/blob/cdd1536997a091dcf9054da9ff424a2603067755/setup.py#L49
