### ISSUE TITLE
Issue in the latest image : OSError: [Errno 30] Read-only file system: '/nonexistent'

### ISSUE THREAD

**Issue by Ulrar** [rhasspy/wyoming-faster-whisper#27]
Hi,

I've been using this image for a while, but the last version seems to complain about something new : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 149, in <module>
    run()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 144, in run
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 119, in main
    whisper_model = faster_whisper.WhisperModel(
  File "/usr/local/lib/python3.9/dist-packages/faster_whisper/transcribe.py", line 146, in __init__
    self.hf_tokenizer = tokenizers.Tokenizer.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 1224, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nonexistent'
```

The filesystem is indeed read only, but it used to be fine using /data and /tmp, not sure where this /nonexistent is coming from ?
This is my deployment : 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-whisper-en
  labels:
    app: wyoming-whisper-en
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wyoming-whisper-en
  template:
    metadata:
      labels:
        app: wyoming-whisper-en
    spec:
      containers:
      - name: wyoming-whisper-en
        image: rhasspy/wyoming-whisper:latest
        imagePullPolicy: IfNotPresent
        args:
        - --model
        - base-int8
        - --language
        - en
        - --data-dir
        - /data
        - --download-dir
        - /data
        ports:
        - protocol: TCP
          name: wyoming
          containerPort: 10300
        volumeMounts:
        - name: tmpfs-data
          mountPath: /data
        - name: tmpfs
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      volumes:
      - name: tmpfs-data
        emptyDir:
      - name: tmpfs
        emptyDir:
```

**Comment by synesthesiam** [comment]
Can you add `--debug` and post the logs here?

**Comment by Ulrar** [comment]
```
DEBUG:__main__:Namespace(model='base-int8', uri='tcp://0.0.0.0:10300', data_dir=['/data', '/data'], download_dir='/data', device='cpu', language='en', compute_type='default', beam_size=5, initial_prompt=None, debug=True, log_format='%(levelname)s:%(name)s:%(message)s')
DEBUG:__main__:Loading rhasspy/faster-whisper-base-int8
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "GET /api/models/rhasspy/faster-whisper-base-int8/revision/main HTTP/1.1" 200 716
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 155, in <module>
    run()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 150, in run
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 124, in main
    whisper_model = faster_whisper.WhisperModel(
  File "/usr/local/lib/python3.9/dist-packages/faster_whisper/transcribe.py", line 146, in __init__
    self.hf_tokenizer = tokenizers.Tokenizer.from_pretrained(
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/huggingface_hub/file_download.py", line 1224, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/nonexistent'
```

Any chance some lib silently depends on an env var I don't have for a temporary directory or something ? I'm for example thinking of go's GOTMPDIR, not sure if there's a python equivalent.

**Comment by Ulrar** [comment]
Looking at it, that's exactly what it is. It's defined there : https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/file_download.py#L109

This fixes the issue : 
```
        env:
          - name: HF_HUB_CACHE
            value: /tmp
```

**Comment by synesthesiam** [comment]
Ah, this makes sense. It defaults to "~/.cache/huggingface/hub" apparently.

I can set it to /tmp in the Dockerfile unless you have any other suggestions.

**Comment by Ulrar** [comment]
Whatever you think I suppose, having it configurable might be best. Maybe just add a note in the readme so if anyone else is using read only root file systems (there's dozens of us !) they'll know what to set ?

**Comment by synesthesiam** [comment]
Added a note the README. Thanks!
