### ISSUE TITLE
Handler exception after no audio i assume

### ISSUE THREAD

**Issue by florian-asche** [rhasspy/wyoming-faster-whisper#38]
Hi, 
i am using wyoming-satellite without vad. I think after i speak the wake word, but nothing else there is a timeout problem inside the wyoming-satellite. That is documented here: https://github.com/rhasspy/wyoming-satellite/issues/237.

But what's not documented is that also wyoming-faster-whisper is crashing and no longer working until i manually restart it. 

I am using the latest docker based version.

Error Log:
```
INFO:__main__:Ready
INFO:faster_whisper:Processing audio with duration 00:03.300
INFO:wyoming_faster_whisper.handler: Wie spät ist es?
INFO:faster_whisper:Processing audio with duration 00:03.980
INFO:wyoming_faster_whisper.handler: Kannst du meine Geschichte vorlesen?
INFO:faster_whisper:Processing audio with duration 00:04.750
INFO:wyoming_faster_whisper.handler: Ich versuche zu verstehen, was du für ein Problem hast.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:31> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 41, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 63, in handle_event
    assert self._wav_file is not None
AssertionError

```

**Comment by synesthesiam** [comment]
Is this still a problem with the Linux Voice Assistant? https://github.com/OHF-Voice/linux-voice-assistant
